version: "3"
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    command: ["streamlit", "run", "main.py", "--server.port=80", "--server.address=0.0.0.0"]
    depends_on:
      - backend
    networks:
      - MusicApp

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]
    # command: sh -c "sleep 20s; python3 test_mysql.py"
    depends_on:
      - database
    networks:
      - MusicApp

  database:
    build:
      context: ./mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'root'
    # volumes:
    #   - db:/docker-entrypoint-initdb.d/
    networks:
      - MusicApp

  tests:
    build:
      context: ./tests
    command: sh -c "sleep 20; pytest"
    depends_on:
      - frontend
    networks:
      - MusicApp

networks:
  MusicApp:
    driver: bridge

